default["jboss"]["url"] = "http://download.jboss.org/wildfly/8.0.0.Final/wildfly-8.0.0.Final.tar.gz"
default["jboss"]["path"] = "/opt/jboss"
default["jboss"]["tmp"] = "/opt/jboss/tmp"
default["jboss"]["user"] = "jboss"
default["jboss"]["testapp_url"] = "http://www.cumulogic.com/download/Apps/testweb.zip"